
package alquilervehiculos;


public class Interfaz extends javax.swing.JFrame {
    //Se declara el objeto valor total de la clase Cacular
    Calcular valortotal = new Calcular();
    private double vlr_total = 0;
        
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_tipoveh = new javax.swing.JComboBox();
        cmb_diasalq = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_vlrtotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa Alquiler de Vehiculos");
        setResizable(false);

        jLabel1.setText("Tipo de Vehiculo");
        jLabel1.setToolTipText("");

        jLabel2.setText("Dias de Alquiler");

        cmb_tipoveh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automovil", "Microbus", "Vehiculo de Carga 18t", "Vehiculo de Carga 26t", "Vehiculo de Carga 32t", "Camion" }));
        cmb_tipoveh.setName("cmb_tipoveh"); // NOI18N
        cmb_tipoveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipovehActionPerformed(evt);
            }
        });

        cmb_diasalq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        cmb_diasalq.setName("cmb_diasalq"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Alquiler de Vehiculos");

        btn_calcular.setText("Calcular");
        btn_calcular.setName("btn_calcular"); // NOI18N
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Valor Total");

        txt_vlrtotal.setEditable(false);
        txt_vlrtotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_vlrtotal.setText("0 COP");
        txt_vlrtotal.setName("txt_vlrtotal"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(cmb_tipoveh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cmb_diasalq, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btn_calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addComponent(txt_vlrtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(cmb_tipoveh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmb_diasalq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_calcular)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_vlrtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarInterfaz(){
        //Estamos haciendo que la Interfaz nos sea visible
        new Interfaz().setVisible(true);
    }
    private void cmb_tipovehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipovehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipovehActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // Declaracion de las variables para tomar e imprimir los datos de la Interfaz
        String tipo_vehiculo = cmb_tipoveh.getSelectedItem().toString();
        int dias_alquiler = Integer.parseInt((String)cmb_diasalq.getSelectedItem());
        
        //Operaciones para determinar que metodo se debe llamar para realizar el calculo del valor total
        switch (tipo_vehiculo) {
            case "Automovil":
                //Se llama el metodo valortotal.vehiculo
                vlr_total = valortotal.vehiculo(dias_alquiler);
                break;
            case "Microbus":
                //Se llama el metodo valortotal.microbus
                vlr_total = valortotal.microbus(dias_alquiler);
                break;
            case "Vehiculo de Carga 18t":
                //Se llama el metodo valor total.vehiculo 18t
                vlr_total = valortotal.vehiculo_18t(dias_alquiler);
            break;
            case "Vehiculo de Carga 26t":
                //Se llama el metodo valor total.vehiculo 26t
                vlr_total = valortotal.vehiculo_26t(dias_alquiler);
            break;
            case "Vehiculo de Carga 32t":
                //Se llama el metodo valor total.vehiculo 32t
                vlr_total = valortotal.vehiculo_32t(dias_alquiler);
            break;
            case "Camion":
                //Se llama el metodo valor total.camion
                vlr_total = valortotal.camion(dias_alquiler);
            break;
                case "Vehiculo de Carga 50t":
                //Se llama el metodo valor total.camion
                vlr_total = valortotal.camion(dias_alquiler);
            break;
                    
        }
        //Se imprime el valor total en el Txt valor total
        txt_vlrtotal.setText(String.valueOf(vlr_total + " COP"));
    
    }//GEN-LAST:event_btn_calcularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JComboBox cmb_diasalq;
    private javax.swing.JComboBox cmb_tipoveh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_vlrtotal;
    // End of variables declaration//GEN-END:variables
}
